In [2]:
import numpy as np

## Answer 1)

In [2]:
np.array(np.arange(2,51,3))

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50])

## Answer 2)

In [33]:
#Making two empty list
listFirst = list()
listSecond = list()

#Taking Input from User 
for i in range(5):
    listFirst.append(int(input("Enter Element in 1st list=>")))
    listSecond.append(int(input("Enter Element in 2nd list=>")))
print()

#Convertinf List into Array
arr1 = np.array(listFirst)
arr2 = np.array(listSecond)

#Printing Both Array
print("\nArray 1st=>",arr1)
print("Array 2nd=>",arr2)

#Concatination of array
print("\nConcationation of Arr1 and Arr2 =>",np.concatenate((arr1,arr2),axis=None))

#Sorting od both array
print("\nSorted arr1=>",np.sort(arr1))
print("Sorted arr2=>",np.sort(arr2))

Enter Element in 1st list=>9
Enter Element in 2nd list=>8
Enter Element in 1st list=>7
Enter Element in 2nd list=>1
Enter Element in 1st list=>4
Enter Element in 2nd list=>5
Enter Element in 1st list=>6
Enter Element in 2nd list=>3
Enter Element in 1st list=>0
Enter Element in 2nd list=>1


Nump array 1st=> [9 7 4 6 0]
Nump array 2nd=> [8 1 5 3 1]

Concationation of Arr1 and Arr2 => [9 7 4 6 0 8 1 5 3 1]

Sorted arr1=> [0 4 6 7 9]
Sorted arr2=> [1 1 3 5 8]


## Answer 3)

In [41]:
array1 = np.array([ [1,2,3,4,5] , [1,2,3,4,5] ])

#Dimension of array
print("It is a",array1.ndim,"dimensional array")
print("Its Size is",array1.size)

It is a 2 dimensional array
Its Size is 10


## Answer 4)

In [49]:
newArray = np.array([1,2,3,4])

print("Multi-D array from 1-D Array:-\n",np.expand_dims(newArray, axis=1))


Multi-D array from 1-D Array:-
 [[1]
 [2]
 [3]
 [4]]


## Answer 5)

In [50]:
#Two Square array
a = np.array([ [1,2,3],[4,5,6],[7,8,9] ])
b = np.array([ [11,12,13],[14,15,16],[17,18,19] ])

#Vertically and Horizontally stacked
print("\nArray 1st vertically stacked:\n",np.vstack(a))
print("Array 1st Horizontally stacked:\n",np.hstack(a))

print("\nArray 2nd vertically stacked:\n",np.vstack(b))
print("Array 2nd Horizontally stacked:\n",np.hstack(b))


Array 1st vertically stacked:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Array 1st Horizontally stacked:
 [1 2 3 4 5 6 7 8 9]

Array 2nd vertically stacked:
 [[11 12 13]
 [14 15 16]
 [17 18 19]]
Array 2nd Horizontally stacked:
 [11 12 13 14 15 16 17 18 19]


## Answer 6)

In [5]:
arrNew = np.array([1,2,2,4,5,7,8,9,3,1,4,10,2,3,5,4,5])

print("Unique array element =>",np.unique(arrNew))
print("Count of Unique array element =>",len(np.unique(arrNew)))

Unique array element => [ 1  2  3  4  5  7  8  9 10]
Count of Unique array element => 9
